# Generated by Django 4.2.1 on 2023-05-25 11:47

import cargo.management.commands.create_number
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='unik_number',
            field=models.CharField(default=cargo.management.commands.create_number.unik_number_creation, editable=False),
        ),
    ]
