# Generated by Django 4.2.1 on 2023-05-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargo_unik_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='unik_number',
            new_name='slug',
        ),
    ]
