# Generated by Django 4.2.1 on 2023-05-25 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_rename_unik_number_cargo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='weigh',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Вес'),
        ),
    ]
