# Generated by Django 4.2.1 on 2023-05-25 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_alter_cargo_weigh'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='weigh',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Вес'),
        ),
    ]
