# Generated by Django 4.2.1 on 2023-05-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_alter_locations_latitude_alter_locations_longtitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='weigh',
        ),
    ]
