# Generated by Django 4.2.1 on 2023-05-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_remove_locations_weigh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='unik_number',
            new_name='slug',
        ),
    ]
