# Generated by Django 4.2.1 on 2023-05-25 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_rename_unik_number_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='weigh',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Вес'),
        ),
    ]
